name: Renovate
on:
  workflow_dispatch:
  workflow_call:

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v40.3.4
        with:
          configurationFile: renovate-config.js
          token: ${{ secrets.GITHUB_TOKEN }}