name: Renovate
on:
  workflow_dispatch:
  workflow_call:
  push:
    paths:
      - "renovate.json5"
      - "renovate-config.js"
      - ".github/workflows/renovate.yml"

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v41
        with:
          configurationFile: renovate-config.js
          token: ${{ secrets.GITHUB_TOKEN }}