name: Renovate
on:
  workflow_dispatch:
  workflow_call:
  push:
    branches:
      - main
    paths:
      - "renovate-action.json"
      - "renovate-config.js"
      - ".github/workflows/renovate.yml"

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v41.0.7
        with:
          configurationFile: renovate-config.js
          token: ${{ secrets.REPO_READ }}
          env-regex: "^(?:RENOVATE_\\w+|LOG_LEVEL|GITHUB_COM_TOKEN|NODE_OPTIONS|AWS_TOKEN|NPM_\\w+)$"
        env:
          LOG_LEVEL: debug
          RENOVATE_DETECT_HOST_RULES_FROM_ENV: "true"
          NPM_NPM_PKG_GITHUB_COM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RENOVATE_FORCE: "true"